#!/usr/bin/env python3
"""
Visualisation du flux décisionnel du robot de trading
"""

def afficher_flux_decisionnel():
    print("=" * 80)
    print("FLUX DÉCISIONNEL DU ROBOT DE TRADING")
    print("=" * 80)
    
    print("\n🔄 BOUCLE PRINCIPALE (toutes les 60 secondes):")
    print("   ↓")
    
    print("\n1️⃣  VÉRIFICATION DES POSITIONS EXISTANTES")
    print("   ├── Scan de toutes les positions ouvertes")
    print("   ├── Vérification si elles existent encore dans MT5")
    print("   ├── Suppression du suivi si positions fermées")
    print("   └── Logging du profit des positions actives")
    print("   ↓")
    
    print("\n2️⃣  PARCOURS DES SYMBOLES (Boom 300, 600, 900, Crash 1000)")
    print("   ↓")
    
    print("\n3️⃣  OBTENTION DU SIGNAL IA")
    print("   ├── Appel API: GET https://kolatradebot.onrender.com/predict/{symbol}")
    print("   ├── Réponse JSON avec:")
    print("   │   ├── direction: 'UP' ou 'DOWN'")
    print("   │   ├── confidence: 0.0 - 1.0 (ex: 0.96 = 96%)")
    print("   │   ├── analysis: trend_strength, volatility, volume, rsi, macd")
    print("   │   └── source: 'render_api' ou 'fallback'")
    print("   ↓")
    
    print("\n4️⃣  FILTRE DE CONFIANCE")
    print("   ├── IF confidence < 70%:")
    print("   │   ├── ❌ IGNORE le signal")
    print("   │   └── 📝 Log: 'Confiance trop faible: X% < 70%'")
    print("   ├── ELSE (confidence >= 70%):")
    print("   │   └── ✅ CONTINUE vers validation")
    print("   ↓")
    
    print("\n5️⃣  VALIDATION DU SIGNAL")
    print("   ├── IF direction != 'BUY' AND direction != 'SELL':")
    print("   │   ├── ❌ IGNORE le signal")
    print("   │   └── 📝 Log: 'Pas de signal trade: NEUTRAL'")
    print("   ├── ELSE:")
    print("   │   └── ✅ CONTINUE vers position check")
    print("   ↓")
    
    print("\n6️⃣  VÉRIFICATION POSITION EXISTANTE")
    print("   ├── IF position déjà ouverte sur ce symbole:")
    print("   │   ├── ❌ IGNORE le signal")
    print("   │   └── 📝 Log: 'Position existante, ignore'")
    print("   ├── ELSE (pas de position):")
    print("   │   └── ✅ CONTINUE vers exécution")
    print("   ↓")
    
    print("\n7️⃣  PRÉPARATION DE L'ORDRE")
    print("   ├── Récupération infos symbole (volume min/max, point, digits)")
    print("   ├── Récupération tick actuel (bid/ask)")
    print("   ├── Calcul SL/TP selon symbole:")
    print("   │   ├── Boom 300: SL=2000pts, TP=4000pts")
    print("   │   ├── Boom 600: SL=1800pts, TP=3600pts")
    print("   │   ├── Boom 900: SL=1500pts, TP=3000pts")
    print("   │   └── Crash 1000: SL=8000pts, TP=16000pts")
    print("   ├── Arrondi SL/TP à 3 décimales (Boom/Crash)")
    print("   └── Construction requête MT5")
    print("   ↓")
    
    print("\n8️⃣  EXÉCUTION DE L'ORDRE")
    print("   ├── mt5.order_send(request)")
    print("   ├── IF result is None:")
    print("   │   ├── ❌ ERREUR: 'mt5.order_send() returned None'")
    print("   │   └── 📝 Log erreur + requête complète")
    print("   ├── IF result.retcode != TRADE_RETCODE_DONE:")
    print("   │   ├── ❌ ORDRE REJETÉ")
    print("   │   ├── 📝 Log: code erreur + commentaire")
    print("   │   ├── IF 'Invalid stops' dans commentaire:")
    print("   │   │   ├── 🔄 ESSAI SANS SL/TP")
    print("   │   │   ├── Nouvelle requête avec sl=0, tp=0")
    print("   │   │   └── IF succès: ✅ Ordre sans stops")
    print("   │   └── ELSE: ❌ Échec final")
    print("   ├── ELSE (succès):")
    print("   │   ├── ✅ ORDRE RÉUSSI!")
    print("   │   ├── 📝 Log: ticket, prix, volume")
    print("   │   ├── 📋 Enregistrement position dans self.positions")
    print("   │   └── 🔄 Retour boucle principale")
    print("   ↓")
    
    print("\n" + "=" * 80)
    print("POINTS CLÉS DU FLUX:")
    print("=" * 80)
    
    print("\n🎯 SEUILS DÉCISIONNELS:")
    print("   • Confiance minimale: 70%")
    print("   • Direction valide: BUY ou SELL uniquement")
    print("   • Position unique par symbole")
    print("   • Type filling: FOK (Fill or Kill)")
    
    print("\n⚡ RYTHME:")
    print("   • Check toutes les 60 secondes")
    print("   • 4 symboles scannés = 1 signal toutes les 15 secondes max")
    print("   • Position tracking en temps réel")
    
    print("\n🛡️ SÉCURITÉ:")
    print("   • Volume fixe par symbole (0.2-0.5)")
    print("   • SL/TP très larges (évite 'Invalid stops')")
    print("   • Fallback sans SL/TP si nécessaire")
    print("   • Magic number unique (234000)")
    
    print("\n📊 LOGGING:")
    print("   • Tentatives d'ordres complètes")
    print("   • Erreurs détaillées avec requêtes")
    print("   • Profits des positions actives")
    print("   • Confiance et direction des signaux")
    
    print("\n" + "=" * 80)
    print("EXEMPLE CONCRET:")
    print("=" * 80)
    
    print("\n📈 SCÉNARIO RÉUSSI:")
    print("   1. Signal reçu: Boom 300 Index, direction=UP, confidence=96%")
    print("   2. ✅ Confiance 96% >= 70% → Continue")
    print("   3. ✅ Direction 'UP' → Signal BUY")
    print("   4. ✅ Pas de position existante → Continue")
    print("   5. 📊 Ask: 1980.273, Volume: 0.5")
    print("   6. 📏 SL: 1978.273 (-2000pts), TP: 1984.273 (+4000pts)")
    print("   7. 📤 Envoi requête MT5 avec type_filling=FOK")
    print("   8. ✅ Ordre réussi: Ticket 5543930557")
    print("   9. 📋 Position enregistrée pour tracking")
    
    print("\n❌ SCÉNARIO REJETÉ:")
    print("   1. Signal reçu: Boom 900 Index, direction=DOWN, confidence=63%")
    print("   2. ❌ Confiance 63% < 70% → Signal ignoré")
    print("   3. 📝 Log: 'Confiance trop faible: 63.0% < 70.0%'")
    print("   4. 🔄 Continue vers symbole suivant")

if __name__ == "__main__":
    afficher_flux_decisionnel()
